import { createChatCompletion } from "./openrouter.js";
import { createExecutionBatches } from "./plan.js";

export async function executeGenerationPlan(plan, env, options = {}) {
  return executeBuildPlan(plan, env, { ...options, review: null, repair: null, maxReviewRounds: 0 });
}

export async function executeBuildPlan(plan, env, options = {}) {
  const generate = options.generate || generateFile;
  const review = options.review === null ? null : options.review || reviewFile;
  const repair = options.repair === null ? null : options.repair || repairFile;
  const onEvent = options.onEvent || (() => {});
  const concurrency = options.concurrency || plan.defaults.concurrency;
  const maxReviewRounds = options.maxReviewRounds ?? plan.defaults.maxReviewRounds;
  const outputs = new Map();
  const batches = createExecutionBatches(plan.tasks);

  onEvent({ type: "start", taskCount: plan.tasks.length, batches: batches.length });

  for (let index = 0; index < batches.length; index += 1) {
    const batch = batches[index];
    onEvent({ type: "batch:start", batch: index + 1, taskIds: batch.map((task) => task.id) });
    await runQueue(batch, concurrency, async (task) => {
      const dependencies = task.dependsOn.map((id) => outputs.get(id)).filter(Boolean);
      onEvent({ type: "task:start", taskId: task.id, path: task.path, model: task.generator });
      const result = await generateReviewedFile({
        plan,
        task,
        dependencies,
        env,
        generate,
        review,
        repair,
        maxReviewRounds,
        onEvent
      });
      outputs.set(task.id, {
        taskId: task.id,
        path: task.path,
        content: result.content,
        model: task.generator,
        reviewer: review ? task.reviewer : null,
        reviews: result.reviews || [],
        knownIssues: result.knownIssues || [],
        usage: result.usage || null
      });
      onEvent({ type: "task:done", taskId: task.id, path: task.path });
    });
    onEvent({ type: "batch:done", batch: index + 1 });
  }

  onEvent({ type: "done", fileCount: outputs.size });
  return [...outputs.values()];
}

export async function generateReviewedFile(context) {
  const { plan, task, dependencies, env, generate, review, repair, maxReviewRounds, onEvent } = context;
  const first = await generate(plan, task, dependencies, env);
  let content = first.content;
  const usage = [first.usage].filter(Boolean);
  const reviews = [];

  for (let round = 1; review && round <= maxReviewRounds; round += 1) {
    onEvent({ type: "review:start", taskId: task.id, round, reviewer: task.reviewer });
    const reviewResult = await review(plan, task, content, dependencies, env, round);
    reviews.push(reviewResult);
    if (reviewResult.usage) usage.push(reviewResult.usage);
    onEvent({
      type: "review:done",
      taskId: task.id,
      round,
      approved: reviewResult.approved,
      issues: reviewResult.issues.length
    });
    if (reviewResult.approved || !repair) {
      break;
    }

    onEvent({ type: "repair:start", taskId: task.id, round, model: task.generator });
    const repairResult = await repair(plan, task, content, reviewResult, dependencies, env, round);
    content = repairResult.content;
    if (repairResult.usage) usage.push(repairResult.usage);
    onEvent({ type: "repair:done", taskId: task.id, round });
  }

  const lastReview = reviews[reviews.length - 1];
  return {
    content,
    reviews,
    knownIssues: lastReview && !lastReview.approved ? lastReview.issues : [],
    usage
  };
}

export async function generateFile(plan, task, dependencies, env) {
  const messages = [
    {
      role: "system",
      content: [
        "You generate one project file from a build plan.",
        "Return only the exact file contents.",
        "Do not wrap the file in Markdown fences.",
        "Do not add explanation outside the file."
      ].join("\n")
    },
    {
      role: "user",
      content: buildGenerationPrompt(plan, task, dependencies)
    }
  ];
  return createChatCompletion(env, {
    model: task.generator,
    messages,
    maxTokens: task.maxOutputTokens,
    temperature: 0.2
  });
}

export async function reviewFile(plan, task, content, dependencies, env, round) {
  const messages = [
    {
      role: "system",
      content: [
        "You are reviewing code generated by a different model family.",
        "Find concrete bugs, missing imports, broken APIs and contract mismatches.",
        "Do not report speculative issues without evidence.",
        "Return strict JSON only."
      ].join("\n")
    },
    {
      role: "user",
      content: buildReviewPrompt(plan, task, content, dependencies, round)
    }
  ];
  const response = await createChatCompletion(env, {
    model: task.reviewer,
    messages,
    maxTokens: 1200,
    temperature: 0.1
  });
  return {
    ...parseReviewJson(response.content),
    raw: response.content,
    usage: response.usage || null
  };
}

export async function repairFile(plan, task, content, review, dependencies, env, round) {
  const messages = [
    {
      role: "system",
      content: [
        "You repair one project file using a reviewer report.",
        "Return only the complete corrected file contents.",
        "Do not wrap the file in Markdown fences."
      ].join("\n")
    },
    {
      role: "user",
      content: buildRepairPrompt(plan, task, content, review, dependencies, round)
    }
  ];
  return createChatCompletion(env, {
    model: task.generator,
    messages,
    maxTokens: task.maxOutputTokens,
    temperature: 0.15
  });
}

export function buildGenerationPrompt(plan, task, dependencies) {
  const dependencyText = dependencies.length
    ? dependencies.map((item) => `## ${item.path}\n${item.content}`).join("\n\n")
    : "No completed dependency files.";

  return [
    `Project: ${plan.projectName}`,
    `Stack: ${plan.stack}`,
    `Target file: ${task.path}`,
    "",
    "Task instruction:",
    task.instruction,
    "",
    "Completed dependency context:",
    dependencyText,
    "",
    "Write the complete target file now."
  ].join("\n");
}

export function buildReviewPrompt(plan, task, content, dependencies, round) {
  return [
    `Project: ${plan.projectName}`,
    `Stack: ${plan.stack}`,
    `Target file: ${task.path}`,
    `Review round: ${round}`,
    "",
    "Task instruction:",
    task.instruction,
    "",
    "Dependency files:",
    dependencies.length ? dependencies.map((item) => `## ${item.path}\n${item.content}`).join("\n\n") : "None",
    "",
    "Generated file:",
    content,
    "",
    "Return JSON in this shape:",
    "{\"approved\":true,\"summary\":\"...\",\"issues\":[]}",
    "{\"approved\":false,\"summary\":\"...\",\"issues\":[{\"severity\":\"high|medium|low\",\"evidence\":\"specific code quote\",\"problem\":\"...\",\"fix\":\"...\"}]}"
  ].join("\n");
}

export function buildRepairPrompt(plan, task, content, review, dependencies, round) {
  return [
    `Project: ${plan.projectName}`,
    `Stack: ${plan.stack}`,
    `Target file: ${task.path}`,
    `Repair round: ${round}`,
    "",
    "Task instruction:",
    task.instruction,
    "",
    "Dependency files:",
    dependencies.length ? dependencies.map((item) => `## ${item.path}\n${item.content}`).join("\n\n") : "None",
    "",
    "Reviewer report:",
    JSON.stringify(review, null, 2),
    "",
    "Current file:",
    content,
    "",
    "Return the complete corrected target file only."
  ].join("\n");
}

export function parseReviewJson(text) {
  const trimmed = String(text || "").trim();
  const jsonText = trimmed.startsWith("{") ? trimmed : extractJsonObject(trimmed);
  const parsed = JSON.parse(jsonText);
  return {
    approved: Boolean(parsed.approved),
    summary: String(parsed.summary || ""),
    issues: Array.isArray(parsed.issues) ? parsed.issues.map(normalizeIssue) : []
  };
}

function extractJsonObject(text) {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) {
    throw new Error("Reviewer did not return JSON");
  }
  return text.slice(start, end + 1);
}

function normalizeIssue(issue) {
  return {
    severity: String(issue.severity || "medium"),
    evidence: String(issue.evidence || ""),
    problem: String(issue.problem || ""),
    fix: String(issue.fix || "")
  };
}

async function runQueue(items, concurrency, worker) {
  const queue = [...items];
  const workers = Array.from({ length: Math.min(concurrency, queue.length) }, async () => {
    while (queue.length > 0) {
      const item = queue.shift();
      await worker(item);
    }
  });
  await Promise.all(workers);
}
