import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

export async function writeBuildOutput(baseDir, plan, outputs, events = []) {
  const runId = `${timestamp()}-${slug(plan.projectName)}`;
  const runDir = join(baseDir, "runs", runId);
  const filesDir = join(runDir, "files");
  await mkdir(filesDir, { recursive: true });

  const files = [];
  for (const output of outputs) {
    const safePath = cleanOutputPath(output.path);
    const content = cleanGeneratedContent(output.content);
    const target = join(filesDir, safePath);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, content, "utf8");
    files.push({ path: safePath, content });
  }

  const handoff = createHandoffReport(plan, outputs);
  const log = JSON.stringify({ plan, outputs: summarizeOutputs(outputs), events }, null, 2);
  const zip = createZipBuffer([
    ...files,
    { path: "HANDOFF.md", content: handoff },
    { path: "build-log.json", content: log }
  ]);

  await writeFile(join(runDir, "HANDOFF.md"), handoff, "utf8");
  await writeFile(join(runDir, "build-log.json"), log, "utf8");
  await writeFile(join(runDir, `${slug(plan.projectName)}.zip`), zip);

  return {
    runId,
    runDir,
    filesDir,
    handoffPath: join(runDir, "HANDOFF.md"),
    logPath: join(runDir, "build-log.json"),
    zipPath: join(runDir, `${slug(plan.projectName)}.zip`)
  };
}

export function createHandoffReport(plan, outputs) {
  const lines = [
    `# ${plan.projectName} Handoff`,
    "",
    "## What Was Built",
    "",
    `- Stack: ${plan.stack}`,
    `- Files generated: ${outputs.length}`,
    `- Budget cap: $${plan.budgetUsd.toFixed(2)}`,
    "",
    "## Files",
    ""
  ];

  for (const output of outputs) {
    lines.push(`- \`${output.path}\` generated by \`${output.model}\`, reviewed by \`${output.reviewer || "none"}\``);
  }

  lines.push("", "## Known Issues", "");
  const issues = outputs.flatMap((output) => (output.knownIssues || []).map((issue) => ({ ...issue, path: output.path })));
  if (issues.length === 0) {
    lines.push("- No static-review issues were left unresolved. Runtime verification still required.");
  } else {
    for (const issue of issues) {
      lines.push(`- \`${issue.path}\` [${issue.severity}]: ${issue.problem} Fix: ${issue.fix}`);
    }
  }

  lines.push(
    "",
    "## Next Steps For Codex Or Claude",
    "",
    "1. Install dependencies.",
    "2. Run the formatter, linter, tests and build command.",
    "3. Launch the app locally and verify the main workflow.",
    "4. Fix runtime errors first, then polish UX and edge cases.",
    "5. Commit the finished changes."
  );

  return `${lines.join("\n")}\n`;
}

export function cleanGeneratedContent(content) {
  const text = String(content || "").trim();
  const match = text.match(/^```[a-zA-Z0-9_-]*\n([\s\S]*?)\n```$/);
  return match ? match[1] : text;
}

export function createZipBuffer(files) {
  const localParts = [];
  const centralParts = [];
  let offset = 0;

  for (const file of files) {
    const name = Buffer.from(cleanOutputPath(file.path));
    const content = Buffer.from(String(file.content), "utf8");
    const crc = crc32(content);
    const local = localHeader(name, content, crc);
    const central = centralHeader(name, content, crc, offset);
    localParts.push(local, content);
    centralParts.push(central);
    offset += local.length + content.length;
  }

  const centralSize = centralParts.reduce((sum, part) => sum + part.length, 0);
  const end = endRecord(files.length, centralSize, offset);
  return Buffer.concat([...localParts, ...centralParts, end]);
}

function summarizeOutputs(outputs) {
  return outputs.map((output) => ({
    taskId: output.taskId,
    path: output.path,
    model: output.model,
    reviewer: output.reviewer,
    reviews: output.reviews,
    knownIssues: output.knownIssues,
    usage: output.usage
  }));
}

function cleanOutputPath(path) {
  const value = String(path).replace(/\\/g, "/").replace(/^\/+/, "");
  if (!value || value.includes("..")) {
    throw new Error(`Unsafe output path: ${path}`);
  }
  return value;
}

function slug(value) {
  return String(value || "draft-project")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 64) || "draft-project";
}

function timestamp() {
  const date = new Date();
  return date.toISOString().replace(/[-:]/g, "").replace(/\..+$/, "").replace("T", "-");
}

function localHeader(name, content, crc) {
  const header = Buffer.alloc(30 + name.length);
  header.writeUInt32LE(0x04034b50, 0);
  header.writeUInt16LE(20, 4);
  header.writeUInt16LE(0, 6);
  header.writeUInt16LE(0, 8);
  header.writeUInt16LE(0, 10);
  header.writeUInt16LE(0, 12);
  header.writeUInt32LE(crc, 14);
  header.writeUInt32LE(content.length, 18);
  header.writeUInt32LE(content.length, 22);
  header.writeUInt16LE(name.length, 26);
  header.writeUInt16LE(0, 28);
  name.copy(header, 30);
  return header;
}

function centralHeader(name, content, crc, offset) {
  const header = Buffer.alloc(46 + name.length);
  header.writeUInt32LE(0x02014b50, 0);
  header.writeUInt16LE(20, 4);
  header.writeUInt16LE(20, 6);
  header.writeUInt16LE(0, 8);
  header.writeUInt16LE(0, 10);
  header.writeUInt16LE(0, 12);
  header.writeUInt16LE(0, 14);
  header.writeUInt32LE(crc, 16);
  header.writeUInt32LE(content.length, 20);
  header.writeUInt32LE(content.length, 24);
  header.writeUInt16LE(name.length, 28);
  header.writeUInt16LE(0, 30);
  header.writeUInt16LE(0, 32);
  header.writeUInt16LE(0, 34);
  header.writeUInt16LE(0, 36);
  header.writeUInt32LE(0, 38);
  header.writeUInt32LE(offset, 42);
  name.copy(header, 46);
  return header;
}

function endRecord(fileCount, centralSize, centralOffset) {
  const header = Buffer.alloc(22);
  header.writeUInt32LE(0x06054b50, 0);
  header.writeUInt16LE(0, 4);
  header.writeUInt16LE(0, 6);
  header.writeUInt16LE(fileCount, 8);
  header.writeUInt16LE(fileCount, 10);
  header.writeUInt32LE(centralSize, 12);
  header.writeUInt32LE(centralOffset, 16);
  header.writeUInt16LE(0, 20);
  return header;
}

function crc32(buffer) {
  let crc = 0xffffffff;
  for (const byte of buffer) {
    crc = (crc >>> 8) ^ CRC_TABLE[(crc ^ byte) & 0xff];
  }
  return (crc ^ 0xffffffff) >>> 0;
}

const CRC_TABLE = Array.from({ length: 256 }, (_, index) => {
  let value = index;
  for (let bit = 0; bit < 8; bit += 1) {
    value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
  }
  return value >>> 0;
});
