const fs = require('fs');
const path = require('path');
const archiver = require('archiver');
const { OUTPUT_DIR } = require('../config');

function safeJoin(root, rel) {
  const target = path.resolve(root, rel);
  const relPath = path.relative(root, target);
  if (relPath.startsWith('..') || path.isAbsolute(relPath)) {
    throw new Error(`invalid file path: ${rel}`);
  }
  return target;
}

function addDirectory(archive, dir, base) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const ent of entries) {
    const full = path.join(dir, ent.name);
    const rel = path.relative(base, full);
    if (ent.name === 'build.zip') continue;
    if (ent.isDirectory()) {
      addDirectory(archive, full, base);
    } else {
      archive.file(full, { name: rel });
    }
  }
}

function buildReceipt(job) {
  return {
    projectName: job.plan.projectName,
    jobId: job.id,
    runId: job.runId,
    createdAt: job.createdAt,
    finishedAt: new Date().toISOString(),
    state: job.state,
    stack: job.plan.stack,
    budgetUsd: job.plan.budgetUsd,
    actualCostUsd: job.costUsd,
    tokens: job.tokens,
    fileCount: job.outputs.size,
    modelsUsed: [...new Set([...job.outputs.values()].map((o) => o.model))],
    knownIssues: job.issues
  };
}

function buildAgentsMd(job) {
  return `# AGENTS.md — ${job.plan.projectName}

## Context
This draft was generated by Prototype Coder via OpenRouter.

## How to continue
1. Review \`HANDOFF.md\` and \`known-issues.md\`.
2. Use Claude Code or Codex to make it run and verify.
3. Do not regenerate from this file using the automated pipeline unless you start a new build.

## Build reference
- Job: \`${job.id}\`
- Run: \`${job.runId}\`
- Files: ${job.outputs.size}
`;
}

function buildHandoffMd(job) {
  return `# HANDOFF.md — ${job.plan.projectName}

**Job:** \`${job.id}\`
**Run:** \`${job.runId}\`
**State:** ${job.state}
**Estimated cost:** ${job.plan.budgetUsd ?? 4} USD
**Actual cost:** ${Math.round(job.costUsd * 10000) / 10000} USD

## Stack
${Array.isArray(job.plan.stack) ? job.plan.stack.join(', ') : job.plan.stack || 'Not specified'}

## Files generated
${[...job.outputs.values()].map((o) => `- ${o.path}`).join('\n')}

## Next steps
Review the generated files in your editor, then hand off to Claude Code or Codex for polish and verification.
`;
}

function buildKnownIssuesMd(job) {
  if (!job.issues.length) return 'No known issues.';
  return job.issues.map((i) => `- **${i.taskId}:** ${i.message}`).join('\n');
}

async function packageBuild(job) {
  const base = path.join(OUTPUT_DIR, job.id);
  fs.mkdirSync(base, { recursive: true });

  for (const [, file] of job.outputs) {
    if (file.path.endsWith('/')) {
      fs.mkdirSync(safeJoin(base, file.path), { recursive: true });
      continue;
    }
    const target = safeJoin(base, file.path);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, file.content, 'utf8');
  }

  fs.writeFileSync(
    path.join(base, 'BUILD_RECEIPT.json'),
    JSON.stringify(buildReceipt(job), null, 2),
    'utf8'
  );
  fs.writeFileSync(path.join(base, 'AGENTS.md'), buildAgentsMd(job), 'utf8');
  fs.writeFileSync(path.join(base, 'HANDOFF.md'), buildHandoffMd(job), 'utf8');
  fs.writeFileSync(
    path.join(base, 'build-log.txt'),
    job.events.map((e) => `[${e.time}] ${e.type} ${JSON.stringify(e.payload)}`).join('\n'),
    'utf8'
  );
  fs.writeFileSync(path.join(base, 'known-issues.md'), buildKnownIssuesMd(job), 'utf8');

  const zipPath = path.join(base, 'build.zip');
  await new Promise((resolve, reject) => {
    const output = fs.createWriteStream(zipPath);
    const archive = archiver('zip', { zlib: { level: 9 } });
    output.on('close', resolve);
    archive.on('error', reject);
    archive.on('warning', (err) => {
      if (err.code === 'ENOENT') console.warn('archiver warning', err);
      else reject(err);
    });
    archive.pipe(output);
    addDirectory(archive, base, base);
    archive.finalize();
  });

  return zipPath;
}

module.exports = { packageBuild };
